### ISSUE TITLE
OpenAttestationDidSignedDocumentStatus verifier throws Cannot read property 'blockTag' of undefined

### ISSUE THREAD

**Issue by kierien** [Open-Attestation/oa-verify#177]
Thanks for all the work on open-attestation! As the title reads, the OpenAttestationDidSignedDocumentStatus verifier throws an 'Cannot read property 'blockTag' of undefined' error on signed documents. The documents passed in have no issue being verified on https://dev.tradetrust.io/ or https://dev.opencerts.io/. 

Below is a reproducible example:
```js
const {
  verificationBuilder,
  openAttestationDidSignedDocumentStatus,
} = require('@govtechsg/oa-verify');
const {
  wrapDocument,
  signDocument,
  SUPPORTED_SIGNING_ALGORITHM,
} = require('@govtechsg/open-attestation');

const verify = verificationBuilder([openAttestationDidSignedDocumentStatus], {
  network: 'ropsten',
});

const main = async () => {
  const document = {
    issuers: [
      {
        id: /*REPLACE THIS*/,
        name: 'Demo Issuer',
        revocation: {
          type: 'NONE',
        },
        identityProof: {
          type: 'DNS-DID',
          location: /*REPLACE THIS*/,
          key: /*REPLACE THIS*/,
        },
      },
    ],
  };

  const wrappedDocument = wrapDocument(document);
  const signedDocument = await signDocument(
    wrappedDocument,
    SUPPORTED_SIGNING_ALGORITHM.Secp256k1VerificationKey2018,
    {
      public: /*REPLACE THIS*/,
      private:
        /*REPLACE THIS*/,
    }
  );
  const fragments = await verify(signedDocument);
  console.log(fragments);
};

main();
```

Results in:
```js
[
  {
    name: 'OpenAttestationDidSignedDocumentStatus',
    type: 'DOCUMENT_STATUS',
    data: TypeError: Cannot read property 'blockTag' of undefined
        at S.resolve (/Users/kierian/Desktop/oa-verify-test/node_modules/ethr-did-resolver/lib/index.umd.js:1:11817)
        at /Users/kierian/Desktop/oa-verify-test/node_modules/did-resolver/lib/resolver.js:1:2147
        at r.t [as cache] (/Users/kierian/Desktop/oa-verify-test/node_modules/did-resolver/lib/resolver.js:1:568)
        at /Users/kierian/Desktop/oa-verify-test/node_modules/did-resolver/lib/resolver.js:1:2121
        at r.resolve (/Users/kierian/Desktop/oa-verify-test/node_modules/did-resolver/lib/resolver.js:1:2259)
        at /Users/kierian/Desktop/oa-verify-test/node_modules/@govtechsg/oa-verify/dist/cjs/did/resolver.js:84:58
        at step (/Users/kierian/Desktop/oa-verify-test/node_modules/@govtechsg/oa-verify/dist/cjs/did/resolver.js:44:23)
        at Object.next (/Users/kierian/Desktop/oa-verify-test/node_modules/@govtechsg/oa-verify/dist/cjs/did/resolver.js:25:53)
        at /Users/kierian/Desktop/oa-verify-test/node_modules/@govtechsg/oa-verify/dist/cjs/did/resolver.js:19:71
        at new Promise (<anonymous>),
    reason: {
      message: "Cannot read property 'blockTag' of undefined",
      code: 1,
      codeString: 'UNEXPECTED_ERROR'
    },
    status: 'ERROR'
  }
]
```

package.json: 
```json
{
  "name": "oa-verify-test",
  "version": "1.0.0",
  "main": "index.js",
  "license": "MIT",
  "dependencies": {
    "@govtechsg/oa-verify": "^7.4.1",
    "@govtechsg/open-attestation": "^5.2.2"
  }
}
```

Codesandbox:
[https://codesandbox.io/s/jovial-gould-8h8eg?file=/index.js](https://codesandbox.io/s/jovial-gould-8h8eg?file=/index.js)

**Comment by cavacado** [comment]
Hi there, thanks for pointing out this issue.

After some amount of investigation, we discovered that one of our dependencies `ethr-did-resolver` has a breaking interface change between 3.0.3 and 3.1.0.

currently we allow minor versions for this particular dependency, but I have just pushed up a fix to pin the dependency to 3.0.3.

once that is up, the error should go away.
